/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.ufpe.cin.residencia.aula;

public class App {
    public String getGreeting() {
        return "Olá mundo!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
